fixtures:
  symlinks:
    monero: "#{source_dir}"
  forge_modules:
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '4.24.0'
    archive:
      repo: 'puppet/archive'
      ref: '2.2.0'
    systemd:
      repo: 'camptocamp/systemd'
      ref: '1.1.1'
