fixtures:
  repositories:
    'stdlib':
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.6.0'
    'firewall':
      repo: 'git://github.com/camptocamp/puppet-systemd.git'
      ref: '1.1.1'
  symlinks:
    boost: "#{source_dir}"
